### ISSUE TITLE
applying gb of 0.0 panics

### ISSUE THREAD

**Issue by berkes** [sonmezonur/initials.rs#3]
When running the `api` and setting the Gaussian Blur attribute to 0.0, the upstream image handler library panics.

```
thread 'arbiter:cbfdb3bc-c80e-4c09-8fda-ed071b613d98:actix-net-worker-3' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'arbiter:9cce60d5-0d0b-48d5-9a49-6e9863a2daf9:actix-net-worker-4' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:a5d9aedc-09bc-478d-a227-ebde6e5b3efb:actix-net-worker-5' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:84f380cd-806f-406d-b45e-534db7db2dd1:actix-net-worker-6' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:54cde202-1eb3-4be2-96f9-b892266a318d:actix-net-worker-7' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:0af1561e-af5a-4055-9cd5-6d9a30f0423d:actix-net-worker-0' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:c3edbad8-562d-4a93-8715-44f3e00a005e:actix-net-worker-1' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:208d35e5-8eb8-4ab2-b5d0-1e563f2b292f:actix-net-worker-2' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
thread 'arbiter:f4bc9ff9-ae2e-4a1c-a7e3-d8f01523eecc:actix-net-worker-8' panicked at 'called `Option::unwrap()` on a `None` value', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.19.0/./src/imageops/sample.rs:266:17
```

**Comment by sonmezonur** [comment]
Hi @berkes 

Thanks for reporting this.  I initiated this project around 2 years ago and have not checked it ever since. It is most likely there is no boundary check on these input types. I marked this issue as a bug and will look into it sooner.

Thanks again

**Comment by berkes** [comment]
No prob. I just noticed this and thought you might at least want to know.

I was looking into rendering the text wit subpixelhinting or anti-aliasing of some sort. And to run that, I needed to "disable" the gaussian-blur. Which, I assume, was implemented as a quick hack for the lack of font-rasterization. Which seems impossible without using the imageproc crate.
